version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: redis
    networks:
      - internal-network
    ports:
      - "8882:6379"
    command: ["bash", "-c", "echo never > /sys/kernel/mm/transparent_hugepage/enabled && redis-server"]
    privileged: true

networks:
  internal-network:
    driver: bridge
